services:
  backend:
    build: ./backend
    ports: ["8000:8000"]
    environment:
      - DATABASE_URL=sqlite:///./rental.db
    volumes:
      - ./backend/app:/app/app
  frontend:
    image: node:20
    working_dir: /app
    command: bash -lc "npm i && npm run dev -- -p 3000"
    ports: ["3000:3000"]
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
